server:
  port: 8080
  servlet:
    context-path: /v1

spring:
  application:
    name: movie-booking-api

  # ==================================
  # C?u hình PostgreSQL Database
  # ==================================
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_booking_db
    username: root
    password: hiep2004
    driver-class-name: org.postgresql.Driver

  # ==================================
  # C?u hình Spring Data JPA / Hibernate
  # ==================================
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Tùy ch?n: T? ??ng t?o/c?p nh?t schema database.
      # C?n thay ??i thành 'none' ho?c 'validate' khi deploy lên môi tr??ng Production.
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true




# ==================================
# C?u hình Springdoc OpenAPI (Swagger)
# ==================================
springdoc:
  swagger-ui:
    path: /api-docs/swagger


openapi:
  service:
    api-docs: api-service
    server: http://localhost:8080/v1
    title: API Service
    version: 1.0.0